-- init_oracle.sql
-- Kullanıcı ve yetkiler (Otomatik oluşur ama garanti olsun)
ALTER SESSION SET CONTAINER=XEPDB1;

-- 1. ÜRÜNLER TABLOSU
CREATE TABLE urunler (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kategori VARCHAR2(50),
    urun_adi VARCHAR2(100),
    fiyat NUMBER(10, 2),
    stok_miktari NUMBER
);

-- 2. SATIŞLAR TABLOSU
CREATE TABLE satislar (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    urun_id NUMBER,
    adet NUMBER,
    toplam_tutar NUMBER(10, 2),
    satis_tarihi DATE DEFAULT SYSDATE,
    musteri_sehir VARCHAR2(50),
    CONSTRAINT fk_urun FOREIGN KEY (urun_id) REFERENCES urunler(id)
);

-- VERİ EKLEME: ÜRÜNLER
INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Elektronik', 'Laptop Pro 15', 35000, 50);
INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Elektronik', 'Kablosuz Mouse', 750, 200);
INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Giyim', 'Kot Pantolon', 1200, 150);
INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Ev', 'Kahve Makinesi', 4500, 30);
INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Spor', 'Yoga Matı', 300, 100);

-- VERİ EKLEME: SATIŞLAR (Geçmiş tarihlerle)
-- Dün satılanlar
INSERT INTO satislar (urun_id, adet, toplam_tutar, satis_tarihi, musteri_sehir) VALUES (1, 1, 35000, SYSDATE - 1, 'Istanbul');
INSERT INTO satislar (urun_id, adet, toplam_tutar, satis_tarihi, musteri_sehir) VALUES (2, 2, 1500, SYSDATE - 1, 'Ankara');

-- 5 gün önce satılanlar
INSERT INTO satislar (urun_id, adet, toplam_tutar, satis_tarihi, musteri_sehir) VALUES (4, 1, 4500, SYSDATE - 5, 'Izmir');

-- 10 gün önce satılanlar
INSERT INTO satislar (urun_id, adet, toplam_tutar, satis_tarihi, musteri_sehir) VALUES (3, 3, 3600, SYSDATE - 10, 'Bursa');

-- EK VERİLER: ÜRÜNLER (hacim artışı)
INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Elektronik', 'Akıllı Telefon X', 28000, 80);
INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Elektronik', 'Bluetooth Kulaklık', 1800, 300);
INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Giyim', 'Spor Tişört', 650, 250);
INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Giyim', 'Mont', 4200, 60);
INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Ev', 'Elektrikli Süpürge', 9200, 40);
INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Ev', 'Blender Seti', 3200, 70);
INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Spor', 'Koşu Ayakkabısı', 3800, 90);
INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Spor', 'Dambıl Seti', 2100, 120);

-- EK VERİLER: SATIŞLAR (son 30 gün – zaman serisi genişletme)

-- Son 2 gün
INSERT INTO satislar VALUES (DEFAULT, 5, 1, 28000, SYSDATE - 2, 'Istanbul');
INSERT INTO satislar VALUES (DEFAULT, 6, 2, 3600,  SYSDATE - 2, 'Ankara');
INSERT INTO satislar VALUES (DEFAULT, 7, 3, 1950,  SYSDATE - 2, 'Izmir');

-- Son 4 gün
INSERT INTO satislar VALUES (DEFAULT, 8, 1, 4200,  SYSDATE - 4, 'Bursa');
INSERT INTO satislar VALUES (DEFAULT, 9, 1, 9200,  SYSDATE - 4, 'Antalya');

-- Son 7 gün
INSERT INTO satislar VALUES (DEFAULT, 10, 2, 6400, SYSDATE - 7, 'Istanbul');
INSERT INTO satislar VALUES (DEFAULT, 11, 1, 3800, SYSDATE - 7, 'Ankara');
INSERT INTO satislar VALUES (DEFAULT, 12, 1, 2100, SYSDATE - 7, 'Izmir');

-- Son 14 gün
INSERT INTO satislar VALUES (DEFAULT, 1, 1, 35000, SYSDATE - 14, 'Istanbul');
INSERT INTO satislar VALUES (DEFAULT, 2, 4, 3000,  SYSDATE - 14, 'Eskisehir');
INSERT INTO satislar VALUES (DEFAULT, 3, 2, 2400,  SYSDATE - 14, 'Konya');

-- Son 21 gün
INSERT INTO satislar VALUES (DEFAULT, 4, 1, 4500,  SYSDATE - 21, 'Izmir');
INSERT INTO satislar VALUES (DEFAULT, 6, 3, 5400,  SYSDATE - 21, 'Ankara');
INSERT INTO satislar VALUES (DEFAULT, 7, 5, 3250,  SYSDATE - 21, 'Istanbul');

-- Son 30 gün
INSERT INTO satislar VALUES (DEFAULT, 8, 2, 8400,  SYSDATE - 30, 'Bursa');
INSERT INTO satislar VALUES (DEFAULT, 9, 1, 9200,  SYSDATE - 30, 'Istanbul');
INSERT INTO satislar VALUES (DEFAULT, 12, 2, 4200, SYSDATE - 30, 'Antalya');

COMMIT;
