from fastapi import APIRouter, Depends
from services.oracle import OracleService
from core.deps import get_oracle_service

router = APIRouter(tags=["Reports Setup"])


@router.get("/setup-db")
async def setup_database(oracle=Depends(get_oracle_service)):
    """
    Eğer tablolar yoksa oluşturur ve test verisi basar.
    Docker volume sorunlarını çözmek için manuel tetikleyici.
    """
    logs = []

    commands = [
        "BEGIN EXECUTE IMMEDIATE 'DROP TABLE satislar'; EXCEPTION WHEN OTHERS THEN NULL; END;",
        "BEGIN EXECUTE IMMEDIATE 'DROP TABLE urunler'; EXCEPTION WHEN OTHERS THEN NULL; END;",
        """
        CREATE TABLE urunler (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            kategori VARCHAR2(50),
            urun_adi VARCHAR2(100),
            fiyat NUMBER(10, 2),
            stok_miktari NUMBER
        )
        """,
        """
        CREATE TABLE satislar (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            urun_id NUMBER,
            adet NUMBER,
            toplam_tutar NUMBER(10, 2),
            satis_tarihi DATE DEFAULT SYSDATE,
            musteri_sehir VARCHAR2(50),
            CONSTRAINT fk_urun FOREIGN KEY (urun_id) REFERENCES urunler(id)
        )
        """,
        "INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Elektronik', 'Laptop Pro 15', 35000, 50)",
        "INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Elektronik', 'Kablosuz Mouse', 750, 200)",
        "INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Giyim', 'Kot Pantolon', 1200, 150)",
        "INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Ev', 'Kahve Makinesi', 4500, 30)",
        "INSERT INTO urunler (kategori, urun_adi, fiyat, stok_miktari) VALUES ('Spor', 'Yoga Matı', 300, 100)",
        "INSERT INTO satislar (urun_id, adet, toplam_tutar, satis_tarihi, musteri_sehir) VALUES (1, 1, 35000, SYSDATE - 1, 'Istanbul')",
        "INSERT INTO satislar (urun_id, adet, toplam_tutar, satis_tarihi, musteri_sehir) VALUES (2, 2, 1500, SYSDATE - 1, 'Ankara')",
        "INSERT INTO satislar (urun_id, adet, toplam_tutar, satis_tarihi, musteri_sehir) VALUES (4, 1, 4500, SYSDATE - 5, 'Izmir')",
        "INSERT INTO satislar (urun_id, adet, toplam_tutar, satis_tarihi, musteri_sehir) VALUES (3, 3, 3600, SYSDATE - 10, 'Bursa')",
    ]

    try:
        for sql in commands:
            try:
                oracle.execute_query(sql)
                logs.append(f"Başarılı: {sql[:30]}...")
            except Exception as e:
                logs.append(f"Hata ({sql[:10]}...): {str(e)}")

        return {"status": "Setup Tamamlandı", "logs": logs}

    except Exception as e:
        return {"status": "Genel Hata", "error": str(e)}

